### PR TITLE
change OpenStream to accept a context

### PR DESCRIPTION
**Pull request by marten-seemann**
Depends on https://github.com/libp2p/go-libp2p-core/pull/172.

### CODE REVIEW

**Comment by willscott** [comment]
should there be an issue for shutting down the stream when the context expires as a follow-on to this?

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
> should there be an issue for shutting down the stream when the context expires as a follow-on to this?

The context is just for opening the stream. This is actually how contexts are _supposed_ to be used, we just tend to abuse them.

**Comment by willscott** [comment]
> > should there be an issue for shutting down the stream when the context expires as a follow-on to this?
> 
> The context is just for opening the stream. This is actually how contexts are _supposed_ to be used, we just tend to abuse them.

Am i correct in reading it that `OpenStream` does block on a network send of a window update indicating the new stream exists:
https://github.com/libp2p/go-yamux/blob/master/session.go#L201

If so, do we need to thread context down to the sending loop to be able to fail out of that blocking?

**Comment by marten-seemann** [comment]
@willscott is right here in that we should not ignore the context entirely, as this PR (which just intends to satisfy the new interface) does. @Stebalien is right that the context should only apply to opening the stream, i.e. it applies only for the duration of `OpenStream`, everything that happens after `OpenStream` has returned doesn't matter.

I opened #30 to track this.

**Review by raulk — COMMENTED** [review]
The context deadline might need to percolate down to the actual network write over the transport, potentially through `SetDeadline`...

**Pull request merged**
